apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: first-pod
spec:
  containers:
    - name: container-pod-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: db-configmap